name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The release version"
        required: true
      branch:
        description: "The branch to release from"
        required: true
        default: 'mainline'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'gradle'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Release on Sonatype
        env:
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_SECRET }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PGP_PASSPHRASE }}
          RELEASE_VERSION: ${{ github.event.inputs.version }}
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository --no-daemon

      - name: Tag Release
        run: |
          git tag v${{ github.event.inputs.version }}
          git push --tags
